---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 15
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"  
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    directory: "/playground"
    schedule:
      interval: "monthly"  
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /integration-test
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: daily
