# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - main: "./cmd/permify"
    env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "windows"
      - "darwin"
    goarch:
      - "amd64"
      - "arm64"
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - "-s -w"
nfpms:
  - vendor: "permify inc."
    homepage: "https://permify.co"
    maintainer: "permify <help@permify.co>"
    description: "Permify is an open-source authorization service & policy engine based on Google Zanzibar."
    license: "Apache 2.0"
    formats:
      - "deb"
      - "rpm"
      - "apk"
dockers:
  # ARM64
  - image_templates:
      - ghcr.io/permify/permify:v{{ .Version }}-arm64
    dockerfile:  Dockerfile.release
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
  # AMD64
  - image_templates:
      - ghcr.io/permify/permify:v{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
docker_manifests:
  # GitHub Registry
  - name_template: ghcr.io/permify/permify:v{{ .Version }}
    image_templates:
      - ghcr.io/permify/permify:v{{ .Version }}-amd64
      - ghcr.io/permify/permify:v{{ .Version }}-arm64
  - name_template: ghcr.io/permify/permify:latest
    image_templates:
      - ghcr.io/permify/permify:v{{ .Version }}-amd64
      - ghcr.io/permify/permify:v{{ .Version }}-arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
