app:
  name: 'permify'
  version: '0.0.1'

http:
  port: '3476'

logger:
  log_level: 'debug'
  rollbar_env: 'permify'

tracer:
  exporter: 'zipkin'
  endpoint: 'http://localhost:9411/api/v2/spans'
  disabled: false

database:
  write:
    connection: 'postgres'
    database: 'db_name'
    uri: 'postgres://user:password@host:5432'
    pool_max: 20