server:
  http:
    enabled: true
    port: 3476
  grpc:
    port: 3478

logger:
  level: 'debug'

authn:
  enabled: false
  keys: []

tracer:
  exporter: 'zipkin'
  endpoint: 'http://localhost:9411/api/v2/spans'
  enabled: true

database:
  engine: 'postgres'
  database: 'db_name'
  uri: 'postgres://user:password@host:5432'
  pool_max: 20