server:
  http:
    enabled: true
    port: 3476
    tls:
      enabled: true
      cert: /etc/letsencrypt/live/yourdomain.com/fullchain.pem
      key: /etc/letsencrypt/live/yourdomain.com/privkey.pem
  grpc:
    port: 3478
    tls:
      enabled: true
      cert: /etc/letsencrypt/live/yourdomain.com/fullchain.pem
      key: /etc/letsencrypt/live/yourdomain.com/privkey.pem

logger:
  level: 'debug'

authn:
  enabled: false
  keys: []

tracer:
  exporter: 'zipkin'
  endpoint: 'http://localhost:9411/api/v2/spans'
  enabled: true

meter:
  exporter: 'otlp'
  endpoint: 'localhost:4318'
  enabled: true

service:
  circuit_breaker: false
  concurrency_limit: 100

database:
  engine: 'postgres'
  uri: 'postgres://user:password@host:5432/db_name'
  max_open_connections: 20