app:
  name: 'permify'

http:
  port: 3476

grpc:
  port: 3478

logger:
  log_level: 'debug'

authn:
  disabled: true
  keys: []

tracer:
  exporter: 'zipkin'
  endpoint: 'http://localhost:9411/api/v2/spans'
  disabled: false

database:
  write:
    connection: 'postgres'
    database: 'db_name'
    uri: 'postgres://user:password@host:5432'
    pool_max: 20