name: Go Test and Coveralls
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ~1.20.2

    - name: Install Coveralls
      run: go get github.com/mattn/goveralls

    - name: Run Tests and Upload Coverage
      run: |
        go test -v -coverprofile=profile.cov ./cmd/... ./internal/... ./pkg/...
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
