---
name: "Release"
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"
permissions:
  contents: "write"
  packages: "write"
jobs:
  goreleaser:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.18"
      - uses: "permify/actions/docker-login@main"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: "docker/setup-buildx-action@v1"
      - uses: "goreleaser/goreleaser-action@v3"
        with:
          distribution: "goreleaser"
          version: "latest"
          args: "release --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
