name: Generate Client SDKs from OpenAPI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Generate Python Client
              uses: openapi-generators/openapitools-generator-action@v1
              with:
                  generator: python
                  openapi-file: docs/apidocs.swagger.json

            - name: Push Python SDK to GitHub
              env:
                  GITHUB_TOKEN: ${{ secrets.SDK_GH_TOKEN }}
                  TARGET_REPO: "permify/permify-python"
              run: |
                  git config --global user.name 'GitHub Actions Bot'
                  git config --global user.email '<>'
                  git clone https://${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git temp
                  cp -r python-client/* temp/
                  cd temp
                  git add .
                  git commit -m "Update Python SDK from OpenAPI changes"
                  git push https://${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git main --force
