---
name: "Conventional Commits"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  contents: read

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - uses: amannn/action-semantic-pull-request@cfb60706e18bc85e8aec535e3c577abe8f70378e # v5.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            enhancement
            revert
            build
            ci
            style
            refactor
            perf
            test
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
